"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { GenerationEvent } from "@/lib/data-layer";

const STYLES = [
  { id: "all", name: "All Styles" },
  { id: "halftone", name: "Halftone" },
  { id: "pixelart", name: "Pixel Art" },
  { id: "hexmosaic", name: "Hex Mosaic" },
  { id: "lowpoly", name: "Low Poly" },
  { id: "lineart", name: "Line Art" },
  { id: "charmosa", name: "Character Mosaic" },
  { id: "heatmap", name: "Contribution Heatmap" },
];

export default function GalleryPage() {
  const [items, setItems] = useState<Array<GenerationEvent & { thumbnailUrl: string }>>([]);
  const [selectedStyle, setSelectedStyle] = useState("all");
  const [loading, setLoading] = useState(true);
  const [nextCursor, setNextCursor] = useState<string | undefined>(undefined);
  const [loadingMore, setLoadingMore] = useState(false);
  const [reportModal, setReportModal] = useState<string | null>(null);
  const [reportReason, setReportReason] = useState("");
  const [reported, setReported] = useState(false);

  useEffect(() => {
    async function loadGallery() {
      setLoading(true);
      try {
        const query = selectedStyle !== "all" ? `?style=${selectedStyle}` : "";
        const res = await fetch(`/api/gallery${query}`);
        const data = await res.json();
        setItems(data.items || []);
        setNextCursor(data.nextCursor);
      } catch {
        setItems([]);
      } finally {
        setLoading(false);
      }
    }
    void loadGallery();
  }, [selectedStyle]);

  async function loadMore() {
    if (!nextCursor || loadingMore) return;
    setLoadingMore(true);
    try {
      const styleParam = selectedStyle !== "all" ? `style=${selectedStyle}&` : "";
      const res = await fetch(`/api/gallery?${styleParam}cursor=${nextCursor}`);
      const data = await res.json();
      setItems((prev) => [...prev, ...(data.items || [])]);
      setNextCursor(data.nextCursor);
    } catch {
      // ignore
    } finally {
      setLoadingMore(false);
    }
  }

  async function handleReport(hash: string) {
    try {
      await fetch("/api/gallery", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "report", hash, reason: reportReason }),
      });
      setItems((prev) => prev.filter((i) => i.hash !== hash));
      setReported(true);
      setTimeout(() => {
        setReportModal(null);
        setReported(false);
        setReportReason("");
      }, 1500);
    } catch {
      // ignore
    }
  }

  return (
    <main className="bg-grid min-h-screen">
      <div className="mx-auto max-w-6xl px-4 pb-24 pt-10 sm:pt-16">
        {/* Navigation Bar */}
        <nav className="mb-10 flex items-center justify-between border-b border-[#30363d] pb-4">
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-[#e6edf3] hover:text-[#39d353]">
            <span className="text-[#39d353]">$</span> gh-avatar-art
          </Link>
          <div className="flex items-center gap-4 text-xs">
            <Link href="/" className="rounded-md border border-[#30363d] bg-[#161b22] px-3 py-1.5 text-[#c9d1d9] hover:border-[#8b949e]">
              ← Generator
            </Link>
            <Link
              href="/"
              className="rounded-md border border-[#238636] bg-[#238636] px-3.5 py-1.5 font-semibold text-white hover:bg-[#2ea043]"
            >
              Generate Yours →
            </Link>
          </div>
        </nav>

        {/* Header */}
        <header className="mb-10 text-center sm:text-left">
          <h1 className="text-3xl font-bold tracking-tight text-[#e6edf3] sm:text-4xl">
            Community Showcase
          </h1>
          <p className="mt-2 max-w-2xl text-sm text-[#8b949e]">
            Browse real GitHub profile artworks generated by developers. Opted-in creations from our community.
          </p>
        </header>

        {/* Style Filters */}
        <div className="mb-8 flex flex-wrap gap-2">
          {STYLES.map((st) => (
            <button
              key={st.id}
              type="button"
              onClick={() => setSelectedStyle(st.id)}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-all ${
                selectedStyle === st.id
                  ? "border border-[#238636] bg-[#238636] text-white"
                  : "border border-[#30363d] bg-[#0d1117] text-[#c9d1d9] hover:border-[#8b949e]"
              }`}
            >
              {st.name}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        {loading ? (
          <div className="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="aspect-square animate-pulse rounded-xl border border-[#30363d] bg-[#161b22]/50" />
            ))}
          </div>
        ) : items.length === 0 ? (
          <div className="rounded-xl border border-[#30363d] bg-[#0d1117] p-12 text-center">
            <p className="text-base font-semibold text-[#e6edf3]">No public artworks in this category yet</p>
            <p className="mt-1 text-xs text-[#7d8590]">Be the first to generate art and check &ldquo;Add to Public Gallery&rdquo;!</p>
            <Link
              href="/"
              className="mt-5 inline-block rounded-lg border border-[#238636] bg-[#238636] px-5 py-2 text-xs font-semibold text-white hover:bg-[#2ea043]"
            >
              Generate Artwork Now
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4">
            {items.map((item) => (
              <div
                key={item.id || item.hash}
                className="group relative overflow-hidden rounded-xl border border-[#30363d] bg-[#0d1117] transition-all hover:-translate-y-1 hover:border-[#39d353] hover:shadow-lg"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={item.thumbnailUrl}
                  alt={`Artwork for ${item.username}`}
                  className="aspect-square w-full object-cover"
                  loading="lazy"
                />
                <div className="border-t border-[#21262d] bg-[#0d1117]/95 p-2.5">
                  <div className="flex items-center justify-between">
                    <span className="truncate text-xs font-semibold text-[#e6edf3]">@{item.username}</span>
                    <span className="rounded bg-[#161b22] px-1.5 py-0.5 font-mono text-[10px] text-[#7d8590]">
                      {item.styleId}
                    </span>
                  </div>
                  <div className="mt-2 flex items-center justify-between">
                    <Link
                      href={`/?u=${encodeURIComponent(item.username)}`}
                      className="text-[11px] font-medium text-[#39d353] hover:underline"
                    >
                      Make one like this →
                    </Link>
                    <button
                      type="button"
                      onClick={() => setReportModal(item.hash)}
                      title="Request removal"
                      className="text-[10px] text-[#484f58] hover:text-[#f85149]"
                    >
                      report
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Load more button */}
        {nextCursor && (
          <div className="mt-10 text-center">
            <button
              type="button"
              disabled={loadingMore}
              onClick={() => void loadMore()}
              className="rounded-lg border border-[#30363d] bg-[#161b22] px-6 py-2.5 text-xs font-semibold text-[#c9d1d9] hover:border-[#8b949e] disabled:opacity-50"
            >
              {loadingMore ? "Loading more…" : "Load More Artworks"}
            </button>
          </div>
        )}

        {/* Removal Request Modal */}
        {reportModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
            <div className="w-full max-w-sm rounded-xl border border-[#30363d] bg-[#0d1117] p-5 shadow-2xl">
              <h3 className="text-sm font-semibold text-[#e6edf3]">Request Artwork Removal</h3>
              <p className="mt-1 text-xs text-[#7d8590]">
                If you are the creator of this profile art and wish to remove it from the public showcase, please confirm below.
              </p>
              {reported ? (
                <p className="mt-4 rounded bg-[#238636]/20 p-2 text-center text-xs font-semibold text-[#39d353]">
                  ✓ Artwork removed from gallery
                </p>
              ) : (
                <>
                  <input
                    type="text"
                    placeholder="Optional reason (e.g. owner request)"
                    value={reportReason}
                    onChange={(e) => setReportReason(e.target.value)}
                    className="mt-3 w-full rounded border border-[#30363d] bg-[#010409] px-2.5 py-1.5 text-xs text-[#e6edf3] outline-none focus:border-[#388bfd]"
                  />
                  <div className="mt-4 flex justify-end gap-2 text-xs">
                    <button
                      type="button"
                      onClick={() => setReportModal(null)}
                      className="rounded border border-[#30363d] px-3 py-1.5 text-[#c9d1d9] hover:bg-[#161b22]"
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={() => void handleReport(reportModal)}
                      className="rounded border border-[#f85149] bg-[#f85149] px-3 py-1.5 font-semibold text-white hover:bg-[#da3633]"
                    >
                      Confirm Removal
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        {/* Footer */}
        <footer className="mt-20 border-t border-[#21262d] pt-6 text-center text-xs text-[#7d8590]">
          <p>
            Only artworks explicitly opted-in by their creators appear here. Need help?{" "}
            <a href="https://github.com/AshuSriwastav07/GitHub-Arts-Creator" target="_blank" rel="noreferrer" className="text-[#58a6ff] hover:underline">
              GitHub Repository
            </a>
          </p>
        </footer>
      </div>
    </main>
  );
}
